#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
train_model_hybrid.py

SimpleNet + Hybrid Loss (BCE + MSE) for HCQT -> pitch salience.

- Load .npz files and splits.json generated by data_set_prep.py
- SimpleNet: a small fully-convolutional 2D CNN (HCQT → salience)
- Loss: λ_bce * BCEWithLogits + λ_mse * MSE(sigmoid(pred), target)
- Log train / val total, bce, mse loss
- Save best model as best_model_hybrid.pth
- Plot loss curves to loss_curve_hybrid.png and loss_components_hybrid.png
- Save per-epoch losses to loss_log_hybrid.csv

Usage (in Colab):
    %cd /content/drive/MyDrive/aca_final_assignment

    !python train_model_hybrid.py \
        --data_dir /content/drive/MyDrive/aca_final_assignment/hcqt_output \
        --batch_size 8 \
        --epochs 30 \
        --segment_frames 512 \
        --lambda_bce 1.0 \
        --lambda_mse 0.1
"""

import argparse
import json
from pathlib import Path
import csv
import time

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt


# ======================= Dataset =======================

class HcqtSalienceDataset(Dataset):
    """
    Dataset for HCQT + salience .npz files.

    - data_dir: folder with *.npz and splits.json (from data_set_prep.py)
    - split: 'train' or 'val'
    - segment_frames: fixed T length for each sample (crop or pad)
    - segments_per_track: how many segments per track
    - random_crop: True for train, False for val
    """
    def __init__(
        self,
        data_dir: str,
        split: str = "train",
        segment_frames: int = 512,
        segments_per_track: int = 8,
        random_crop: bool = True,
    ):
        super().__init__()
        self.data_dir = Path(data_dir)
        self.split = split
        self.segment_frames = segment_frames
        self.segments_per_track = segments_per_track
        self.random_crop = random_crop

        # Load split file
        split_path = self.data_dir / "splits.json"
        with split_path.open("r") as f:
            splits = json.load(f)

        if split not in splits:
            raise ValueError(f"Split '{split}' not found in {split_path}")

        self.track_ids = splits[split]
        if len(self.track_ids) == 0:
            raise RuntimeError(f"No tracks in split '{split}'")

        # Cache loaded npz files to reduce disk I/O
        self._cache = {}

        self.num_tracks = len(self.track_ids)
        # Each track is repeated `segments_per_track` times, with different crops
        self._length = self.num_tracks * self.segments_per_track

        print(
            f"[{split}] tracks: {self.num_tracks}, "
            f"segments_per_track: {self.segments_per_track}, "
            f"total samples: {self._length}"
        )

    def __len__(self):
        return self._length

    def _load_npz(self, track_id):
        """Load a single track's npz from disk (with simple in-memory cache)."""
        if track_id in self._cache:
            return self._cache[track_id]

        path = self.data_dir / f"{track_id}.npz"
        if not path.exists():
            raise FileNotFoundError(path)

        data = np.load(path)
        hcqt = data["hcqt"]        # (H, F, T)
        salience = data["salience"]  # (F, T)
        self._cache[track_id] = (hcqt, salience)
        return hcqt, salience

    def _crop_or_pad(self, hcqt, salience):
        """
        Crop or zero-pad a track to a fixed time length.

        hcqt: (H, F, T)
        salience: (F, T)
        -> segment of shape (H, F, segment_frames), (F, segment_frames)
        """
        H, F_bins, T = hcqt.shape
        seg_T = self.segment_frames

        if T >= seg_T:
            if self.random_crop:
                # For training: random crop in time
                start = np.random.randint(0, T - seg_T + 1)
            else:
                # For validation: center crop
                start = max(0, (T - seg_T) // 2)
            end = start + seg_T
            hcqt_seg = hcqt[:, :, start:end]
            sal_seg = salience[:, start:end]
        else:
            # If too short, zero-pad at the end in time dimension
            pad = seg_T - T
            hcqt_seg = np.pad(
                hcqt,
                pad_width=((0, 0), (0, 0), (0, pad)),
                mode="constant",
            )
            sal_seg = np.pad(
                salience,
                pad_width=((0, 0), (0, pad)),
                mode="constant",
            )
        return hcqt_seg, sal_seg

    def __getitem__(self, idx):
        # Map global sample index to track index
        track_idx = idx // self.segments_per_track
        track_id = self.track_ids[track_idx]

        hcqt, salience = self._load_npz(track_id)
        hcqt_seg, sal_seg = self._crop_or_pad(hcqt, salience)

        # Log-compress HCQT for better numerical stability
        hcqt_seg = np.log1p(hcqt_seg).astype(np.float32)

        # Convert to torch tensor, channel-first
        x = torch.from_numpy(hcqt_seg)   # (H, F, T)
        y = torch.from_numpy(sal_seg)    # (F, T)

        return x, y


# ======================= Model (SimpleNet) =======================

class SimpleNet(nn.Module):
    """
    Simple fully-convolutional network for HCQT -> salience.

    Input:  (B, C=H, F, T)
    Output: (B, F, T) logits
    """
    def __init__(self, in_channels=6, hidden_channels=64):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, hidden_channels, kernel_size=3, padding=1)
        self.bn1   = nn.BatchNorm2d(hidden_channels)

        self.conv2 = nn.Conv2d(hidden_channels, hidden_channels, kernel_size=3, padding=1)
        self.bn2   = nn.BatchNorm2d(hidden_channels)

        self.conv3 = nn.Conv2d(hidden_channels, hidden_channels, kernel_size=3, padding=1)
        self.bn3   = nn.BatchNorm2d(hidden_channels)

        # 1x1 conv to project to 1-channel salience logits
        self.conv_out = nn.Conv2d(hidden_channels, 1, kernel_size=1)

    def forward(self, x):
        # x: (B, C, F, T)
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        x = self.conv_out(x)     # (B, 1, F, T)
        x = x.squeeze(1)         # (B, F, T)
        return x


# ======================= Hybrid Loss (BCE + MSE) =======================

class HybridBCEMSELoss(nn.Module):
    """
    Hybrid loss:
        L = λ_bce * BCEWithLogits(logits, target)
          + λ_mse * MSE(sigmoid(logits), target)

    - BCE focuses on bin-level on/off decisions (is there F0 at this bin?)
    - MSE focuses on the overall salience shape (Gaussian-blurred energy distribution)
    """
    def __init__(self, lambda_bce=1.0, lambda_mse=0.1):
        super().__init__()
        self.lambda_bce = lambda_bce
        self.lambda_mse = lambda_mse
        self.bce = nn.BCEWithLogitsLoss()
        self.mse = nn.MSELoss()

    def forward(self, logits, target):
        """
        logits: (B, F, T)
        target: (B, F, T)
        """
        loss_bce = self.bce(logits, target)
        probs = torch.sigmoid(logits)
        loss_mse = self.mse(probs, target)

        loss = self.lambda_bce * loss_bce + self.lambda_mse * loss_mse
        # Return total loss and the individual components for logging
        return loss, {"bce": loss_bce.detach(), "mse": loss_mse.detach()}


# ======================= Training Utils =======================

def set_seed(seed: int = 42):
    """Set random seeds for reproducibility."""
    import random
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    total_bce = 0.0
    total_mse = 0.0
    num_batches = 0

    for x, y in loader:
        x = x.to(device)      # (B, H, F, T)
        y = y.to(device)      # (B, F, T)

        optimizer.zero_grad()
        logits = model(x)     # (B, F, T)

        loss, parts = criterion(logits, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_bce  += parts["bce"].item()
        total_mse  += parts["mse"].item()
        num_batches += 1

    denom = max(1, num_batches)
    return (
        total_loss / denom,
        total_bce / denom,
        total_mse / denom,
    )


@torch.no_grad()
def eval_one_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = 0.0
    total_bce = 0.0
    total_mse = 0.0
    num_batches = 0

    for x, y in loader:
        x = x.to(device)
        y = y.to(device)

        logits = model(x)
        loss, parts = criterion(logits, y)

        total_loss += loss.item()
        total_bce  += parts["bce"].item()
        total_mse  += parts["mse"].item()
        num_batches += 1

    denom = max(1, num_batches)
    return (
        total_loss / denom,
        total_bce / denom,
        total_mse / denom,
    )


def plot_losses(train_tot, val_tot, train_bce, val_bce, train_mse, val_mse, out_dir: Path):
    epochs = np.arange(1, len(train_tot) + 1)

    # Total loss curve
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, train_tot, label="Train total loss")
    plt.plot(epochs, val_tot, label="Val total loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Train / Val Total Loss (Hybrid)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    png_path = out_dir / "loss_curve_hybrid.png"
    plt.savefig(png_path, dpi=200)
    plt.close()
    print(f"Saved total loss curve to {png_path}")

    # BCE / MSE component curves (optional but useful for analysis)
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, train_bce, label="Train BCE")
    plt.plot(epochs, val_bce, label="Val BCE")
    plt.plot(epochs, train_mse, label="Train MSE")
    plt.plot(epochs, val_mse, label="Val MSE")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("BCE / MSE Components")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    png_parts = out_dir / "loss_components_hybrid.png"
    plt.savefig(png_parts, dpi=200)
    plt.close()
    print(f"Saved loss components curve to {png_parts}")


def save_loss_csv(train_tot, val_tot, train_bce, val_bce, train_mse, val_mse, out_path: Path):
    """Save per-epoch loss values into a CSV file."""
    with out_path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "epoch",
            "train_total", "val_total",
            "train_bce", "val_bce",
            "train_mse", "val_mse",
        ])
        for i in range(len(train_tot)):
            writer.writerow([
                i + 1,
                train_tot[i], val_tot[i],
                train_bce[i], val_bce[i],
                train_mse[i], val_mse[i],
            ])
    print(f"Saved loss log to {out_path}")


# ======================= Main =======================

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_dir", type=str, required=True,
                        help="Folder with *.npz and splits.json")
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--segment_frames", type=int, default=512)
    parser.add_argument("--segments_per_track_train", type=int, default=8)
    parser.add_argument("--segments_per_track_val", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--num_workers", type=int, default=2)
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument("--lambda_bce", type=float, default=1.0,
                        help="Weight for BCE term in hybrid loss")
    parser.add_argument("--lambda_mse", type=float, default=0.1,
                        help="Weight for MSE term in hybrid loss")

    args = parser.parse_args()

    set_seed(args.seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Using device:", device)

    # Dataset & DataLoader
    train_ds = HcqtSalienceDataset(
        data_dir=args.data_dir,
        split="train",
        segment_frames=args.segment_frames,
        segments_per_track=args.segments_per_track_train,
        random_crop=True,
    )
    val_ds = HcqtSalienceDataset(
        data_dir=args.data_dir,
        split="val",
        segment_frames=args.segment_frames,
        segments_per_track=args.segments_per_track_val,
        random_crop=False,
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
    )

    # Model
    sample_hcqt, _ = train_ds[0]
    in_channels = sample_hcqt.shape[0]
    print("Input channels (harmonics):", in_channels)

    model = SimpleNet(in_channels=in_channels).to(device)

    # Hybrid loss & optimizer
    criterion = HybridBCEMSELoss(
        lambda_bce=args.lambda_bce,
        lambda_mse=args.lambda_mse,
    )
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    # Logging containers
    train_tot, val_tot = [], []
    train_bce, val_bce = [], []
    train_mse, val_mse = [], []

    best_val = float("inf")
    best_epoch = -1
    out_dir = Path(args.data_dir)
    ckpt_path = out_dir / "best_model_hybrid.pth"
    csv_path = out_dir / "loss_log_hybrid.csv"

    # Training loop
    for epoch in range(1, args.epochs + 1):
        t0 = time.time()
        tr_tot, tr_bce, tr_mse = train_one_epoch(model, train_loader, criterion, optimizer, device)
        va_tot, va_bce, va_mse = eval_one_epoch(model, val_loader, criterion, device)
        t1 = time.time()

        train_tot.append(tr_tot)
        val_tot.append(va_tot)
        train_bce.append(tr_bce)
        val_bce.append(va_bce)
        train_mse.append(tr_mse)
        val_mse.append(va_mse)

        print(
            f"Epoch {epoch:03d} | "
            f"train_total={tr_tot:.4f} (bce={tr_bce:.4f}, mse={tr_mse:.4f}) | "
            f"val_total={va_tot:.4f} (bce={va_bce:.4f}, mse={va_mse:.4f}) | "
            f"time={t1 - t0:.1f}s"
        )

        # Save best model according to validation total loss
        if va_tot < best_val:
            best_val = va_tot
            best_epoch = epoch
            torch.save(model.state_dict(), ckpt_path)
            print(f"  -> New best model saved (epoch {epoch}, val_total={va_tot:.4f})")

    print(f"Training done. Best val_total={best_val:.4f} at epoch {best_epoch}.")

    # Plot & save logs
    plot_losses(train_tot, val_tot, train_bce, val_bce, train_mse, val_mse, out_dir)
    save_loss_csv(train_tot, val_tot, train_bce, val_bce, train_mse, val_mse, csv_path)


if __name__ == "__main__":
    main()
